services:
  - type: web
    name: merc-tool-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "gunicorn --worker-class aiohttp.worker.GunicornWebWorker 'main:init_app()'"
