services:
  - type: web
    name: merc-tool-bot
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python main.py"
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        fromSecret: "TELEGRAM_BOT_TOKEN"  # tu token en Render Secret
      - key: DATABASE_URL
        fromDatabase:
          name: merc-tool-db
          property: connectionString

databases:
  - name: merc-tool-db
    plan: free
